#pragma once

#define SPAXER_SETTINGS_FIELDS(X) \
    X(watermark, Toggle) \
    X(bomb_timer, Toggle) \
    X(crosshair, Toggle) \
    X(esp, Toggle) \
    X(esp_box, Toggle) \
    X(esp_health, Toggle) \
    X(esp_name, Toggle) \
    X(esp_weapon, Toggle) \
    X(esp_team_check, Toggle) \
    X(esp_skeleton, Toggle) \
    X(esp_head_circle, Toggle) \
    X(esp_bone_debug, Toggle) \
    X(sniper_crosshair, Toggle) \
    X(no_flash, Toggle) \
    X(no_smoke, Toggle) \
    X(smoke_color_enabled, Toggle) \
    X(smoke_color_rgba, Color) \
    X(trigger_flash_check, Toggle) \
    X(aimbot_flash_check, Toggle) \
    X(rcs_enabled, Toggle) \
    X(rcs_strength_x100, Number) \
    X(spectators, Toggle) \
    X(keybinds, Toggle) \
    X(radar_hack, Toggle) \
    X(hitmarker, Toggle) \
    X(sound_esp, Toggle) \
    X(crosshair_size, Number) \
    X(crosshair_gap, Number) \
    X(crosshair_thickness, Number) \
    X(crosshair_color_rgba, Color) \
    X(crosshair_dot, Toggle) \
    X(crosshair_outline, Toggle) \
    X(trigger_enabled, Toggle) \
    X(trigger_hitchance, Number) \
    X(trigger_delay_ms, Number) \
    X(trigger_fov_x100, Number) \
    X(trigger_aim_correction, Toggle) \
    X(trigger_shift_fire, Toggle) \
    X(aimbot_enabled, Toggle) \
    X(aimbot_fov_x100, Number) \
    X(aimbot_smooth_x100, Number) \
    X(aimbot_sens_x1000, Number) \
    X(aimbot_thru_walls, Toggle) \
    X(aimbot_point_head, Toggle) \
    X(aimbot_point_neck, Toggle) \
    X(aimbot_point_chest, Toggle) \
    X(aimbot_point_pelvis, Toggle) \
    X(bind_aimbot, Bind) \
    X(snap_tap, Toggle) \
    X(bunnyhop, Toggle) \
    X(auto_strafe, Toggle) \
    X(hud_wm_x, Number) \
    X(hud_wm_y, Number) \
    X(hud_bomb_x, Number) \
    X(hud_bomb_y, Number) \
    X(hud_keybinds_x, Number) \
    X(hud_keybinds_y, Number) \
    X(bind_toggle_gui, Bind) \
    X(bind_edit_hud, Bind) \
    X(bind_trigger, Bind) \
    X(bind_watermark, Bind) \
    X(bind_bomb, Bind) \
    X(bind_crosshair, Bind) \
    X(bind_esp, Bind) \
    X(bind_snap_tap, Bind) \
    X(bind_bunnyhop, Bind) \
    X(bind_auto_strafe, Bind) \
    X(bind_keybinds, Bind) \
    X(arrows, Toggle) \
    X(thirdperson, Toggle) \
    X(esp_dropped_weapons, Toggle) \
    X(grenade_trajectory, Toggle) \
    X(bind_thirdperson, Bind) \
    X(bind_arrows, Bind) \
    X(glow, Toggle) \
    X(glow_team, Toggle) \
    X(glow_enemy_rgba, Color) \
    X(glow_team_rgba, Color) \
    X(bind_glow, Bind) \
    X(radar, Toggle) \
    X(hud_radar_x, Number) \
    X(hud_radar_y, Number) \
    X(bhop_auto_jump, Toggle) \
    X(aimbot_key_mode, Number) \
    X(aimbot_target_mode, Number) \
    X(aimbot_lock, Toggle) \
    X(aimbot_switch_delay_ms, Number) \
    X(chams, Toggle) \
    X(chams_team, Toggle) \
    X(chams_tint, Toggle) \
    X(chams_visible_rgba, Color) \
    X(chams_hidden_rgba, Color) \
    X(chams_team_rgba, Color) \
    X(bind_chams, Bind) \
    X(chams_material, Number) \
    X(chams_hide_model, Number) \
    X(render_lead_ms, Number) \
    X(bind_sound_esp, Bind) \
    X(sound_esp_rgba, Color) \
    X(bind_weapon_esp, Bind) \
    X(weapon_esp_rgba, Color) \
    X(weapon_esp_distance_m, Number) \
    X(arrows_rgba, Color) \
    X(arrows_radius, Number) \
    X(arrows_size, Number) \
    X(aimbot_humanize, Toggle) \
    X(aimbot_speed_min_x100, Number) \
    X(aimbot_speed_max_x100, Number) \
    X(aimbot_shake_x100, Number) \
    X(aimbot_release_x100, Number) \
    X(auto_strafe_mode, Number)
